# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: enable corepack
        run: corepack enable

      - name: install dependencies
        run: yarn install --immutable

        #👇 Adds Chromatic as a step in the workflow
      - name: deployment
        uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
